slack:
    webhook: https://hooks.slack.com/...

openstack:
    auth_url: https://keystone.rc.nectar.org.au:5000/v2.0/
    username: ...
    password: ...
    tenant: ...
    region: ...
    flavor: ...
    security_group: ...
    image:
        base: ...
        prefix: some-prefix-
    swift:
        container: ...
        object: ...
